[dataset]
path = "start/dataset/aimers"
cache = true
batch_size = 256
shuffle = true
num_workers = 0
drop_last = false

[transformations]
seed = 0
cat_encoding = "__none__"
cat_nan_policy = "new_category"
num_nan_policy = "mean"
y_policy = "default"

[graph]
type = "block_uniform"

[noise]
type = "geometric"
sigma_min = 1e-3
sigma_max = 1.0

[model]
type = "resnet"
is_y_cond = false
dim_t = 256

[model.rtdl_params]
n_blocks = 6
d_main = 512
d_hidden = 1024
dropout_first = 0.1
dropout_second = 0.0

[optim]
optimizer = "AdamW"
lr = 2e-4
beta1 = 0.9
beta2 = 0.999
eps = 1e-8
weight_decay = 1e-5
warmup = 500
grad_clip = 1.0

[train]
epochs = 50
grad_accum = 2
log_every = 50
eval_every = 500
checkpoint_every = 1000
checkpoint_dir = "checkpoints/tab_sedd"
ema_decay = 0.999
seed = 777
